### ISSUE TITLE
[sc-text] value attribute is not working

### ISSUE THREAD

**Issue by etiennedemoulin** [ircam-ismm/sc-components#22]
Back in town (:
Trying to set `
<sc-text value='toto'></sc-text>
`

but it's not working.
`
<sc-text>toto</sc-text> 
`
is working.

++

**Comment by b-ma** [comment]
Heiho,

I have made a small test and I can't reproduce the issue, the code is here https://github.com/ircam-ismm/sc-components/blob/main/tests/src/test-sc-text.js and the output is 

<img width="597" alt="Screenshot 2023-08-29 at 09 35 18" src="https://github.com/ircam-ismm/sc-components/assets/1013757/c4cfc6a6-8aa2-409c-9d82-9ef34060504b">

(you can run it locally with `npm run test`)

Could you make sure you have the lastest version installed?

**Comment by etiennedemoulin** [comment]
everything is fine, sorry :)
