### ISSUE TITLE
sc-slider and sc-select behave badly with lit keyed

### ISSUE THREAD

**Issue by etiennedemoulin** [ircam-ismm/sc-components#8]
Expected
<img width="451" alt="Screenshot 2023-07-16 at 10 22 27" src="https://github.com/ircam-ismm/sc-components/assets/46328289/9da5a044-5f72-4e6a-a36d-482aff0e470d">

With lit Keyed
<img width="746" alt="Screenshot 2023-07-16 at 10 23 08" src="https://github.com/ircam-ismm/sc-components/assets/46328289/4004013f-5463-4dcd-8fca-641040a72ad0">

(can be found on lamb.demoul.in/controller)

**Comment by b-ma** [comment]
I cannot reproduce the issue, that's weird

**Comment by etiennedemoulin** [comment]
You can check lamb.demoul.in/controller and https://github.com/etiennedemoulin/nodes-lamb/blob/main/src/clients/controller/index.js

**Comment by b-ma** [comment]
Hum ok,

Seems like you have 2 issues:
- first the select has no `options` proprety which is why it is empty I guess
- second your slider looks like an old "sized" version 

Could you just delete your node_modules and reinstall everything? (that could be a cache issue)

**Comment by b-ma** [comment]
Yup but they are built separately so some problems can appear...

Actually I can see that you are also using the the old `simple-components` lib here: https://github.com/etiennedemoulin/nodes-lamb/blob/93bd802e829d3a858d85f190e6c6d2be04e56cad/src/clients/components/sw-player.js#L7C2-L10 (then the first loaded wins..., I think if you just `import @ircam/sc-components` in `clients/controller/index.js` that will work, but its _really **really**_ dirty :)

Maybe recheck everything to make sure that you are not using `@ircam/simple-components`, remove it from the package.json. I will also try to deprecate it today so at least we have a warning if it is installed by some dependencies. I think I updated everything but maybe I missed something.

(sorry this transition period is a bit boring)

**Comment by etiennedemoulin** [comment]
oh good catch ! i didn't notice :o
i'll update right now

**Comment by etiennedemoulin** [comment]
solved, sorry :-)

**Comment by b-ma** [comment]
Cool!
