### ISSUE TITLE
[sc-tab] background color when selected doesn't fill entire box

### ISSUE THREAD

**Issue by agolvet** [ircam-ismm/sc-components#9]
<img width="406" alt="Capture d’écran 2023-07-21 à 15 30 55" src="https://github.com/ircam-ismm/sc-components/assets/47045936/f0390db2-0df3-44e1-88c5-559b2d2f8013">

happens when placed in header in soundworks default layout

**Comment by b-ma** [comment]
Should be fixed in [3.0.0-alpha.13](https://github.com/ircam-ismm/sc-components/commit/cbc6b060ace40c17dfd78a9fc513912f70d2328a)

Just note that the behaviour of `sc-text` has been changed cf. #1  and https://ircam-ismm.github.io/sc-components/sc-text
